name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - run: npm run lint --if-present
    - run: npm test
    - run: npm run build --if-present
      env:
        CI: true
