"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PACE_CAR_CLASS_ID = exports.VideoCaptureMode = exports.FFBCommandMode = exports.CarLeftRight = exports.PaceFlags = exports.PaceMode = exports.PitServiceStatus = exports.PitServiceFlags = exports.CameraState = exports.SessionState = exports.TrackSurface = exports.TrackLocation = exports.Flags = void 0;
var Flags;
(function (Flags) {
    Flags[Flags["Checkered"] = 1] = "Checkered";
    Flags[Flags["White"] = 2] = "White";
    Flags[Flags["Green"] = 4] = "Green";
    Flags[Flags["Yellow"] = 8] = "Yellow";
    Flags[Flags["Red"] = 16] = "Red";
    Flags[Flags["Blue"] = 32] = "Blue";
    Flags[Flags["Debris"] = 64] = "Debris";
    Flags[Flags["Crossed"] = 128] = "Crossed";
    Flags[Flags["YellowWaving"] = 256] = "YellowWaving";
    Flags[Flags["OneLapToGreen"] = 512] = "OneLapToGreen";
    Flags[Flags["GreenHeld"] = 1024] = "GreenHeld";
    Flags[Flags["TenToGo"] = 2048] = "TenToGo";
    Flags[Flags["FiveToGo"] = 4096] = "FiveToGo";
    Flags[Flags["RandomWaving"] = 8192] = "RandomWaving";
    Flags[Flags["Caution"] = 16384] = "Caution";
    Flags[Flags["CautionWaving"] = 32768] = "CautionWaving";
    Flags[Flags["Black"] = 65536] = "Black";
    Flags[Flags["Disqualify"] = 131072] = "Disqualify";
    Flags[Flags["Servicible"] = 262144] = "Servicible";
    Flags[Flags["Furled"] = 524288] = "Furled";
    Flags[Flags["Repair"] = 1048576] = "Repair";
    Flags[Flags["StartHidden"] = 268435456] = "StartHidden";
    Flags[Flags["StartReady"] = 536870912] = "StartReady";
    Flags[Flags["StartSet"] = 1073741824] = "StartSet";
    Flags[Flags["StartGo"] = 2147483648] = "StartGo";
})(Flags = exports.Flags || (exports.Flags = {}));
var TrackLocation;
(function (TrackLocation) {
    TrackLocation[TrackLocation["NotInWorld"] = -1] = "NotInWorld";
    TrackLocation[TrackLocation["OffTrack"] = 0] = "OffTrack";
    TrackLocation[TrackLocation["InPitStall"] = 1] = "InPitStall";
    TrackLocation[TrackLocation["ApproachingPits"] = 2] = "ApproachingPits";
    TrackLocation[TrackLocation["OnTrack"] = 3] = "OnTrack";
})(TrackLocation = exports.TrackLocation || (exports.TrackLocation = {}));
var TrackSurface;
(function (TrackSurface) {
    TrackSurface[TrackSurface["NotInWorld"] = -1] = "NotInWorld";
    TrackSurface[TrackSurface["Undefined"] = 0] = "Undefined";
    TrackSurface[TrackSurface["Asphalt_1"] = 1] = "Asphalt_1";
    TrackSurface[TrackSurface["Asphalt_2"] = 2] = "Asphalt_2";
    TrackSurface[TrackSurface["Asphalt_3"] = 3] = "Asphalt_3";
    TrackSurface[TrackSurface["Asphalt_4"] = 4] = "Asphalt_4";
    TrackSurface[TrackSurface["Concrete_1"] = 5] = "Concrete_1";
    TrackSurface[TrackSurface["Concrete_2"] = 6] = "Concrete_2";
    TrackSurface[TrackSurface["RacingDirt_1"] = 7] = "RacingDirt_1";
    TrackSurface[TrackSurface["RacingDirt_2"] = 8] = "RacingDirt_2";
    TrackSurface[TrackSurface["Paint_1"] = 9] = "Paint_1";
    TrackSurface[TrackSurface["Paint_2"] = 10] = "Paint_2";
    TrackSurface[TrackSurface["Rumble_1"] = 11] = "Rumble_1";
    TrackSurface[TrackSurface["Rumble_2"] = 12] = "Rumble_2";
    TrackSurface[TrackSurface["Rumble_3"] = 13] = "Rumble_3";
    TrackSurface[TrackSurface["Rumble_4"] = 14] = "Rumble_4";
    TrackSurface[TrackSurface["Grass_1"] = 15] = "Grass_1";
    TrackSurface[TrackSurface["Grass_2"] = 16] = "Grass_2";
    TrackSurface[TrackSurface["Grass_3"] = 17] = "Grass_3";
    TrackSurface[TrackSurface["Grass_4"] = 18] = "Grass_4";
    TrackSurface[TrackSurface["Dirt_1"] = 19] = "Dirt_1";
    TrackSurface[TrackSurface["Dirt_2"] = 20] = "Dirt_2";
    TrackSurface[TrackSurface["Dirt_3"] = 21] = "Dirt_3";
    TrackSurface[TrackSurface["Dirt_4"] = 22] = "Dirt_4";
    TrackSurface[TrackSurface["Sand"] = 23] = "Sand";
    TrackSurface[TrackSurface["Gravel_1"] = 24] = "Gravel_1";
    TrackSurface[TrackSurface["Gravel_2"] = 25] = "Gravel_2";
    TrackSurface[TrackSurface["Grasscrete"] = 26] = "Grasscrete";
    TrackSurface[TrackSurface["Astroturf"] = 27] = "Astroturf";
})(TrackSurface = exports.TrackSurface || (exports.TrackSurface = {}));
var SessionState;
(function (SessionState) {
    SessionState[SessionState["Invalid"] = 0] = "Invalid";
    SessionState[SessionState["GetInCar"] = 1] = "GetInCar";
    SessionState[SessionState["Warmup"] = 2] = "Warmup";
    SessionState[SessionState["ParadeLaps"] = 3] = "ParadeLaps";
    SessionState[SessionState["Racing"] = 4] = "Racing";
    SessionState[SessionState["Checkered"] = 5] = "Checkered";
    SessionState[SessionState["CoolDown"] = 6] = "CoolDown";
})(SessionState = exports.SessionState || (exports.SessionState = {}));
var CameraState;
(function (CameraState) {
    CameraState[CameraState["IsSessionScreen"] = 1] = "IsSessionScreen";
    CameraState[CameraState["IsScenicActive"] = 2] = "IsScenicActive";
    CameraState[CameraState["CamToolActive"] = 4] = "CamToolActive";
    CameraState[CameraState["UiHidden"] = 8] = "UiHidden";
    CameraState[CameraState["UseAutoShotSelection"] = 16] = "UseAutoShotSelection";
    CameraState[CameraState["UseTemporaryEdits"] = 32] = "UseTemporaryEdits";
    CameraState[CameraState["UseKeyAcceleration"] = 64] = "UseKeyAcceleration";
    CameraState[CameraState["UseKey10xAcceleration"] = 128] = "UseKey10xAcceleration";
    CameraState[CameraState["UseMouseAimMode"] = 256] = "UseMouseAimMode";
})(CameraState = exports.CameraState || (exports.CameraState = {}));
var PitServiceFlags;
(function (PitServiceFlags) {
    PitServiceFlags[PitServiceFlags["LFChange"] = 1] = "LFChange";
    PitServiceFlags[PitServiceFlags["RFChange"] = 2] = "RFChange";
    PitServiceFlags[PitServiceFlags["LRChange"] = 4] = "LRChange";
    PitServiceFlags[PitServiceFlags["RRChange"] = 8] = "RRChange";
    PitServiceFlags[PitServiceFlags["Fuel"] = 16] = "Fuel";
    PitServiceFlags[PitServiceFlags["WindshieldTearoff"] = 32] = "WindshieldTearoff";
    PitServiceFlags[PitServiceFlags["FastRepair"] = 64] = "FastRepair";
})(PitServiceFlags = exports.PitServiceFlags || (exports.PitServiceFlags = {}));
var PitServiceStatus;
(function (PitServiceStatus) {
    PitServiceStatus[PitServiceStatus["None"] = 0] = "None";
    PitServiceStatus[PitServiceStatus["InProgress"] = 1] = "InProgress";
    PitServiceStatus[PitServiceStatus["Complete"] = 2] = "Complete";
    PitServiceStatus[PitServiceStatus["TooFarLeft"] = 100] = "TooFarLeft";
    PitServiceStatus[PitServiceStatus["TooFarRight"] = 101] = "TooFarRight";
    PitServiceStatus[PitServiceStatus["TooFarForward"] = 102] = "TooFarForward";
    PitServiceStatus[PitServiceStatus["TooFarBack"] = 103] = "TooFarBack";
    PitServiceStatus[PitServiceStatus["BadAngle"] = 104] = "BadAngle";
    PitServiceStatus[PitServiceStatus["CantFixThat"] = 105] = "CantFixThat";
})(PitServiceStatus = exports.PitServiceStatus || (exports.PitServiceStatus = {}));
var PaceMode;
(function (PaceMode) {
    PaceMode[PaceMode["SingleFileStart"] = 0] = "SingleFileStart";
    PaceMode[PaceMode["DoubleFileStart"] = 1] = "DoubleFileStart";
    PaceMode[PaceMode["SingleFileRestart"] = 2] = "SingleFileRestart";
    PaceMode[PaceMode["DoubleFileRestart"] = 3] = "DoubleFileRestart";
    PaceMode[PaceMode["NotPacing"] = 4] = "NotPacing";
})(PaceMode = exports.PaceMode || (exports.PaceMode = {}));
var PaceFlags;
(function (PaceFlags) {
    PaceFlags[PaceFlags["EndOfLine"] = 1] = "EndOfLine";
    PaceFlags[PaceFlags["FreePass"] = 2] = "FreePass";
    PaceFlags[PaceFlags["WavedAround"] = 4] = "WavedAround";
})(PaceFlags = exports.PaceFlags || (exports.PaceFlags = {}));
var CarLeftRight;
(function (CarLeftRight) {
    CarLeftRight[CarLeftRight["Clear"] = 1] = "Clear";
    CarLeftRight[CarLeftRight["CarLeft"] = 2] = "CarLeft";
    CarLeftRight[CarLeftRight["CarRight"] = 3] = "CarRight";
    CarLeftRight[CarLeftRight["CarLeftRight"] = 4] = "CarLeftRight";
    CarLeftRight[CarLeftRight["TwoCarsLeft"] = 5] = "TwoCarsLeft";
    CarLeftRight[CarLeftRight["TwoCarsRight"] = 6] = "TwoCarsRight";
})(CarLeftRight = exports.CarLeftRight || (exports.CarLeftRight = {}));
var FFBCommandMode;
(function (FFBCommandMode) {
    FFBCommandMode[FFBCommandMode["FFBCommandMaxForce"] = 0] = "FFBCommandMaxForce";
})(FFBCommandMode = exports.FFBCommandMode || (exports.FFBCommandMode = {}));
var VideoCaptureMode;
(function (VideoCaptureMode) {
    VideoCaptureMode[VideoCaptureMode["TriggerScreenShot"] = 0] = "TriggerScreenShot";
    VideoCaptureMode[VideoCaptureMode["StartVideoCapture"] = 1] = "StartVideoCapture";
    VideoCaptureMode[VideoCaptureMode["EndVideoCapture"] = 2] = "EndVideoCapture";
    VideoCaptureMode[VideoCaptureMode["ToggleVideoCapture"] = 3] = "ToggleVideoCapture";
    VideoCaptureMode[VideoCaptureMode["ShowVideoTimer"] = 4] = "ShowVideoTimer";
    VideoCaptureMode[VideoCaptureMode["HideVideoTimer"] = 5] = "HideVideoTimer";
})(VideoCaptureMode = exports.VideoCaptureMode || (exports.VideoCaptureMode = {}));
exports.PACE_CAR_CLASS_ID = 11;
