name: Run Code Coverage
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          
      - name: Install dependencies
        run: yarn install
        
      - name: Build packages
        run: yarn build
        
      - name: Run the tests
        run: yarn test --coverage
        
      - name: Upload coverage
        uses: codecov/codecov-action@v2
